export const currencyNames = {
  RUB: "Russian Rubel",
  CAD: "Canadian Dollar",
  HKD: "Hong Kong Dollar",
  ISK: "Icelandic Krona",
  PHP: "Philippine Peso",
  DKK: "Danish Krone",
  HUF: "Hungarian Forint",
  CZK: "Czech Koruna",
  GBP: "British Pound",
  RON: "Romanian Leu",
  SEK: "Swedish Krona",
  IDR: "Indonesian Rupiah",
  INR: "Indian Rupee",
  BRL: "Brazilian Real",
  HRK: "Croatian Kuna",
  JPY: "Japanese Yen",
  THB: "Thai Baht",
  CHF: "Swiss Franc",
  EUR: "Euro",
  MYR: "Malaysian Ringgit",
  BGN: "Bulgarian Lev",
  TRY: "Turkish Lira",
  CNY: "Chinese Yuan Renminbi",
  NOK: "Norwegian Krone",
  NZD: "New Zealand Dollar",
  ZAR: "South African Rand",
  USD: "US Dollar",
  MXN: "Mexican Peso",
  SGD: "Singapore Dollar",
  AUD: "Australian Dollar",
  ILS: "Israeli Shekel",
  KRW: "South Korean Won",
  PLN: "Polish Zloty",
};
